CREATE TABLE OBD_PPR_PLANTILLA_PRG (
   PPR_CODIGO INT NOT NULL,
   PPR_CODGRC INT NOT NULL,
   PPR_NOMBRE VARCHAR2(250 CHAR) NOT NULL,
   PPR_DESCRIPCION VARCHAR2(4000 CHAR),
   PPR_OBJETIVO VARCHAR2(4000 CHAR),
   PPR_ESTADO VARCHAR2(10 CHAR) DEFAULT ('Activo') NOT NULL,
   PPR_DURACION_ESTIMADA INT DEFAULT ((0)) NOT NULL,
   PPR_UNIDAD_DURACION VARCHAR2(50 CHAR) DEFAULT ('Dias') NOT NULL,
   PPR_PROPERTY_BAG_DATA CLOB,
   PPR_USUARIO_GRABACION VARCHAR2(50 CHAR),
   PPR_FECHA_GRABACION DATE,
   PPR_USUARIO_MODIFICACION VARCHAR2(50 CHAR),
   PPR_FECHA_MODIFICACION DATE
);

COMMENT ON TABLE OBD_PPR_PLANTILLA_PRG IS 'Tabla que almacena la plantilla para los programas de onboarding';

COMMENT ON COLUMN OBD_PPR_PLANTILLA_PRG.PPR_CODIGO IS 'Código de plantilla de programa de onboarding';
COMMENT ON COLUMN OBD_PPR_PLANTILLA_PRG.PPR_CODGRC IS 'Código de Grupo Corporativo';
COMMENT ON COLUMN OBD_PPR_PLANTILLA_PRG.PPR_NOMBRE IS 'Nombre del programa de onboarding';
COMMENT ON COLUMN OBD_PPR_PLANTILLA_PRG.PPR_DESCRIPCION IS 'Descripción del programa de onboarding';
COMMENT ON COLUMN OBD_PPR_PLANTILLA_PRG.PPR_OBJETIVO IS 'Objetivos del programa de onboarding';
COMMENT ON COLUMN OBD_PPR_PLANTILLA_PRG.PPR_ESTADO IS 'Estado de la plantilla ''Activa'' o ''Inactiva''  (inactivas para fines de guardar históricos y que no aparezcan en la selección)';
COMMENT ON COLUMN OBD_PPR_PLANTILLA_PRG.PPR_DURACION_ESTIMADA IS 'Duración estimada del programa';
COMMENT ON COLUMN OBD_PPR_PLANTILLA_PRG.PPR_UNIDAD_DURACION IS 'Unidad de medida de la duración estimada del programa';
COMMENT ON COLUMN OBD_PPR_PLANTILLA_PRG.PPR_PROPERTY_BAG_DATA IS 'Data de los campos adicionales';
COMMENT ON COLUMN OBD_PPR_PLANTILLA_PRG.PPR_USUARIO_GRABACION IS 'Usuario que creo el registro';
COMMENT ON COLUMN OBD_PPR_PLANTILLA_PRG.PPR_FECHA_GRABACION IS 'Fecha en que se creo el registro';
COMMENT ON COLUMN OBD_PPR_PLANTILLA_PRG.PPR_USUARIO_MODIFICACION IS 'Usuario que modificó por última vez el registro';
COMMENT ON COLUMN OBD_PPR_PLANTILLA_PRG.PPR_FECHA_MODIFICACION IS 'Fecha de la última modificacion del registro';
