CREATE TABLE OBD_TAC_TIPOS_ACTIVIDAD (
   TAC_CODIGO INT NOT NULL,
   TAC_CODGRC INT NOT NULL,
   TAC_NOMBRE VARCHAR2(100 CHAR) NOT NULL,
   TAC_DESCRIPCION VARCHAR2(500 CHAR),
   TAC_REQ_NOTIFICACION NUMBER(1, 0) DEFAULT ((0)) NOT NULL,
   TAC_REQ_RECORDATORIO NUMBER(1, 0) DEFAULT ((0)) NOT NULL,
   TAC_REQ_EVALUACION NUMBER(1, 0) DEFAULT ((0)) NOT NULL,
   TAC_REQ_DOCUMENTOS NUMBER(1, 0) DEFAULT ((0)) NOT NULL,
   TAC_REQ_RESPONSABLE NUMBER(1, 0) DEFAULT ((0)) NOT NULL,
   TAC_DURACION_ESTIMADA INT DEFAULT ((0)) NOT NULL,
   TAC_UNIDAD_DURACION VARCHAR2(50 CHAR) DEFAULT ('Dias') NOT NULL,
   TAC_PROPERTY_BAG_DATA CLOB,
   TAC_USUARIO_GRABACION VARCHAR2(50 CHAR),
   TAC_FECHA_GRABACION DATE,
   TAC_USUARIO_MODIFICACION VARCHAR2(50 CHAR),
   TAC_FECHA_MODIFICACION DATE
);

COMMENT ON TABLE OBD_TAC_TIPOS_ACTIVIDAD IS 'Tabla que almacena los tipos de actividad para los programas de Onboarding';

COMMENT ON COLUMN OBD_TAC_TIPOS_ACTIVIDAD.TAC_CODIGO IS 'Código de tipo de actividad';
COMMENT ON COLUMN OBD_TAC_TIPOS_ACTIVIDAD.TAC_CODGRC IS 'Código de grupo corporativo';
COMMENT ON COLUMN OBD_TAC_TIPOS_ACTIVIDAD.TAC_NOMBRE IS 'Nombre del tipo de actividad';
COMMENT ON COLUMN OBD_TAC_TIPOS_ACTIVIDAD.TAC_DESCRIPCION IS 'Descripción del tipo de actividad';
COMMENT ON COLUMN OBD_TAC_TIPOS_ACTIVIDAD.TAC_REQ_NOTIFICACION IS '¿Requiere Notificación luego de que finalice? (contratado, jefe, RRHH y al responsable de la actividad si está definido)';
COMMENT ON COLUMN OBD_TAC_TIPOS_ACTIVIDAD.TAC_REQ_RECORDATORIO IS '¿Requiere Recordatorio previo a que se inicie? (contratado, jefe, RRHH y al responsable de la actividad si está definido)';
COMMENT ON COLUMN OBD_TAC_TIPOS_ACTIVIDAD.TAC_REQ_EVALUACION IS '¿Requiere Evaluación del responsable? (contratado, jefe, RRHH y al responsable de la actividad si está definido)';
COMMENT ON COLUMN OBD_TAC_TIPOS_ACTIVIDAD.TAC_REQ_DOCUMENTOS IS '¿Requiere Adjuntar documentos?';
COMMENT ON COLUMN OBD_TAC_TIPOS_ACTIVIDAD.TAC_REQ_RESPONSABLE IS '¿Requiere un responsable asignado?';
COMMENT ON COLUMN OBD_TAC_TIPOS_ACTIVIDAD.TAC_DURACION_ESTIMADA IS 'Duración estimada de la actividad';
COMMENT ON COLUMN OBD_TAC_TIPOS_ACTIVIDAD.TAC_UNIDAD_DURACION IS 'Unidad de medida para la duración estimada';
COMMENT ON COLUMN OBD_TAC_TIPOS_ACTIVIDAD.TAC_PROPERTY_BAG_DATA IS 'Data de los campos adicionales';
COMMENT ON COLUMN OBD_TAC_TIPOS_ACTIVIDAD.TAC_USUARIO_GRABACION IS 'Usuario que creo el registro';
COMMENT ON COLUMN OBD_TAC_TIPOS_ACTIVIDAD.TAC_FECHA_GRABACION IS 'Fecha en que se creo el registro';
COMMENT ON COLUMN OBD_TAC_TIPOS_ACTIVIDAD.TAC_USUARIO_MODIFICACION IS 'Usuario que modificó por última vez el registro';
COMMENT ON COLUMN OBD_TAC_TIPOS_ACTIVIDAD.TAC_FECHA_MODIFICACION IS 'Fecha de la última modificacion del registro';
