CREATE TABLE OBD_PRI_PRIORIDADES (
   PRI_CODIGO INT NOT NULL,
   PRI_CODGRC INT NOT NULL,
   PRI_NOMBRE VARCHAR2(50 CHAR) NOT NULL,
   PRI_COLOR VARCHAR2(20 CHAR) DEFAULT ('#A9A9A9') NOT NULL,
   PRI_ORDEN INT DEFAULT ((0)) NOT NULL,
   PRI_PROPERTY_BAG_DATA CLOB,
   PRI_USUARIO_GRABACION VARCHAR2(50 CHAR),
   PRI_FECHA_GRABACION DATE,
   PRI_USUARIO_MODIFICACION VARCHAR2(50 CHAR),
   PRI_FECHA_MODIFICACION DATE
);

COMMENT ON TABLE OBD_PRI_PRIORIDADES IS 'Tabla que almacena las prioridades de las actividades del plan de onboarding';

COMMENT ON COLUMN OBD_PRI_PRIORIDADES.PRI_CODIGO IS 'Código de la prioridad';
COMMENT ON COLUMN OBD_PRI_PRIORIDADES.PRI_CODGRC IS 'Código de Grupo Corporativo';
COMMENT ON COLUMN OBD_PRI_PRIORIDADES.PRI_NOMBRE IS 'Nombre de la prioridad';
COMMENT ON COLUMN OBD_PRI_PRIORIDADES.PRI_COLOR IS 'Color con que se muestra la prioridad';
COMMENT ON COLUMN OBD_PRI_PRIORIDADES.PRI_ORDEN IS 'Determina el orden las prioridades';
COMMENT ON COLUMN OBD_PRI_PRIORIDADES.PRI_PROPERTY_BAG_DATA IS 'Data de los campos adicionales';
COMMENT ON COLUMN OBD_PRI_PRIORIDADES.PRI_USUARIO_GRABACION IS 'Usuario que creo el registro';
COMMENT ON COLUMN OBD_PRI_PRIORIDADES.PRI_FECHA_GRABACION IS 'Fecha en que se creo el registro';
COMMENT ON COLUMN OBD_PRI_PRIORIDADES.PRI_USUARIO_MODIFICACION IS 'Usuario que modificó por última vez el registro';
COMMENT ON COLUMN OBD_PRI_PRIORIDADES.PRI_FECHA_MODIFICACION IS 'Fecha de la última modificacion del registro';
