CREATE TABLE OBD_PRO_PROGRAMAS (
   PRO_CODIGO INT NOT NULL,
   PRO_CODPPR INT NOT NULL,
   PRO_NOMBRE VARCHAR2(250 CHAR) NOT NULL,
   PRO_DESCRIPCION VARCHAR2(4000 CHAR),
   PRO_OBJETIVO VARCHAR2(4000 CHAR),
   PRO_ESTADO VARCHAR2(15 CHAR) DEFAULT ('Planificado') NOT NULL,
   PRO_DURACION INT DEFAULT ((0)) NOT NULL,
   PRO_UNIDAD_DURACION VARCHAR2(50 CHAR) DEFAULT ('Dias') NOT NULL,
   PRO_PROPERTY_BAG_DATA CLOB,
   PRO_USUARIO_GRABACION VARCHAR2(50 CHAR),
   PRO_FECHA_GRABACION DATE,
   PRO_USUARIO_MODIFICACION VARCHAR2(50 CHAR),
   PRO_FECHA_MODIFICACION DATE
);

COMMENT ON TABLE OBD_PRO_PROGRAMAS IS 'Tabla que almacena los programas de onboarding';

COMMENT ON COLUMN OBD_PRO_PROGRAMAS.PRO_CODIGO IS 'Código de programa de onboarding';
COMMENT ON COLUMN OBD_PRO_PROGRAMAS.PRO_CODPPR IS 'Código de plantilla programa';
COMMENT ON COLUMN OBD_PRO_PROGRAMAS.PRO_NOMBRE IS 'Nombre del programa de onboarding';
COMMENT ON COLUMN OBD_PRO_PROGRAMAS.PRO_DESCRIPCION IS 'Descripción del programa de onboarding';
COMMENT ON COLUMN OBD_PRO_PROGRAMAS.PRO_OBJETIVO IS 'Objetivos del programa de onboarding';
COMMENT ON COLUMN OBD_PRO_PROGRAMAS.PRO_ESTADO IS 'Estado del programa ''Planificado'' o ''EnEjecucion'' o ''Finalizado''';
COMMENT ON COLUMN OBD_PRO_PROGRAMAS.PRO_DURACION IS 'Duración estimada del programa';
COMMENT ON COLUMN OBD_PRO_PROGRAMAS.PRO_UNIDAD_DURACION IS 'Unidad de medida de la duración estimada del programa';
COMMENT ON COLUMN OBD_PRO_PROGRAMAS.PRO_PROPERTY_BAG_DATA IS 'Data de los campos adicionales';
COMMENT ON COLUMN OBD_PRO_PROGRAMAS.PRO_USUARIO_GRABACION IS 'Usuario que creo el registro';
COMMENT ON COLUMN OBD_PRO_PROGRAMAS.PRO_FECHA_GRABACION IS 'Fecha en que se creo el registro';
COMMENT ON COLUMN OBD_PRO_PROGRAMAS.PRO_USUARIO_MODIFICACION IS 'Usuario que modificó por última vez el registro';
COMMENT ON COLUMN OBD_PRO_PROGRAMAS.PRO_FECHA_MODIFICACION IS 'Fecha de la última modificacion del registro';
