CREATE TABLE OBD_PAC_PLANT_ACTIVIDADES (
   PAC_CODIGO INT NOT NULL,
   PAC_CODPPR INT NOT NULL,
   PAC_NOMBRE VARCHAR2(250 CHAR) NOT NULL,
   PAC_DESCRIPCION VARCHAR2(4000 CHAR),
   PAC_OBJETIVO VARCHAR2(4000 CHAR),
   PAC_CODETP INT NOT NULL,
   PAC_CODTAC INT NOT NULL,
   PAC_OFFSET_INICIO INT DEFAULT ((0)) NOT NULL,
   PAC_UNIDAD_OFFSET_INICIO VARCHAR2(50 CHAR) DEFAULT ('Dias') NOT NULL,
   PAC_DURACION_ESTIMADA INT DEFAULT ((0)) NOT NULL,
   PAC_UNIDAD_DURACION VARCHAR2(50 CHAR) DEFAULT ('Dias') NOT NULL,
   PAC_CODPRI INT NOT NULL,
   PAC_ORDEN INT DEFAULT ((0)) NOT NULL,
   PAC_CODTRA INT NOT NULL,
   PAC_CODTEV INT NOT NULL,
   PAC_NOTA_EVAL_ESPERADA NUMBER(5, 2) DEFAULT ((0)) NOT NULL,
   PAC_PROPERTY_BAG_DATA CLOB,
   PAC_USUARIO_GRABACION VARCHAR2(50 CHAR),
   PAC_FECHA_GRABACION DATE,
   PAC_USUARIO_MODIFICACION VARCHAR2(50 CHAR),
   PAC_FECHA_MODIFICACION DATE
);

COMMENT ON TABLE OBD_PAC_PLANT_ACTIVIDADES IS 'Tabla que almacena las actividades de la plantilla del programa de onboarding';

COMMENT ON COLUMN OBD_PAC_PLANT_ACTIVIDADES.PAC_CODIGO IS 'Código de registro de la actividad de la plantilla para programa de onboarding';
COMMENT ON COLUMN OBD_PAC_PLANT_ACTIVIDADES.PAC_CODPPR IS 'Código de la plantilla de programa de onboarding';
COMMENT ON COLUMN OBD_PAC_PLANT_ACTIVIDADES.PAC_NOMBRE IS 'Nombre de la actividad';
COMMENT ON COLUMN OBD_PAC_PLANT_ACTIVIDADES.PAC_DESCRIPCION IS 'Descripción de la actividad';
COMMENT ON COLUMN OBD_PAC_PLANT_ACTIVIDADES.PAC_OBJETIVO IS 'Objetivo de la actividad';
COMMENT ON COLUMN OBD_PAC_PLANT_ACTIVIDADES.PAC_CODETP IS 'Código de Etapa o Fase del programa';
COMMENT ON COLUMN OBD_PAC_PLANT_ACTIVIDADES.PAC_CODTAC IS 'Código de Tipo de Actividad';
COMMENT ON COLUMN OBD_PAC_PLANT_ACTIVIDADES.PAC_OFFSET_INICIO IS 'Desplazamiento de tiempo antes o despues de la contratación para determinar la fecha de inicio de la actividad';
COMMENT ON COLUMN OBD_PAC_PLANT_ACTIVIDADES.PAC_UNIDAD_OFFSET_INICIO IS 'Unidad de medida del desplazamiento';
COMMENT ON COLUMN OBD_PAC_PLANT_ACTIVIDADES.PAC_DURACION_ESTIMADA IS 'Duración estimada de la actividad';
COMMENT ON COLUMN OBD_PAC_PLANT_ACTIVIDADES.PAC_UNIDAD_DURACION IS 'Unidad de medida de la duración estimada de la actividad';
COMMENT ON COLUMN OBD_PAC_PLANT_ACTIVIDADES.PAC_CODPRI IS 'Código de Prioridad de la actividad';
COMMENT ON COLUMN OBD_PAC_PLANT_ACTIVIDADES.PAC_ORDEN IS 'Orden de esta actividad respecto de las mismas que tienen los mismos requisitos';
COMMENT ON COLUMN OBD_PAC_PLANT_ACTIVIDADES.PAC_CODTRA IS 'Código de Tipo de Responsable de la actividad, cuando es NULL el responsable es el nuevo empleado';
COMMENT ON COLUMN OBD_PAC_PLANT_ACTIVIDADES.PAC_CODTEV IS 'Codigo de Tipo de Evaluación de la activdidad';
COMMENT ON COLUMN OBD_PAC_PLANT_ACTIVIDADES.PAC_NOTA_EVAL_ESPERADA IS 'Nota de evaluación esperada para determinar si aprobo o no la evaluación';
COMMENT ON COLUMN OBD_PAC_PLANT_ACTIVIDADES.PAC_PROPERTY_BAG_DATA IS 'Data de los campos adicionales';
COMMENT ON COLUMN OBD_PAC_PLANT_ACTIVIDADES.PAC_USUARIO_GRABACION IS 'Usuario que creo el registro';
COMMENT ON COLUMN OBD_PAC_PLANT_ACTIVIDADES.PAC_FECHA_GRABACION IS 'Fecha en que se creo el registro';
COMMENT ON COLUMN OBD_PAC_PLANT_ACTIVIDADES.PAC_USUARIO_MODIFICACION IS 'Usuario que modificó por última vez el registro';
COMMENT ON COLUMN OBD_PAC_PLANT_ACTIVIDADES.PAC_FECHA_MODIFICACION IS 'Fecha de la última modificacion del registro';
