CREATE TABLE OBD_ACP_ACTIVIDADES_PRG (
   ACP_CODIGO INT NOT NULL,
   ACP_CODPAP INT NOT NULL,
   ACP_NOMBRE VARCHAR2(250 CHAR) NOT NULL,
   ACP_DESCRIPCION VARCHAR2(4000 CHAR),
   ACP_OBJETIVO VARCHAR2(4000 CHAR),
   ACP_CODETP INT NOT NULL,
   ACP_CODTAC INT NOT NULL,
   ACP_CODEMP_RESPONSABLE INT,
   ACP_FECHA_INICIO DATE NOT NULL,
   ACP_FECHA_FIN DATE NOT NULL,
   ACP_DURACION INT DEFAULT ((0)) NOT NULL,
   ACP_UNIDAD_DURACION VARCHAR2(50 CHAR) DEFAULT ('Dias') NOT NULL,
   ACP_CODPRI INT NOT NULL,
   ACP_ORDEN INT DEFAULT ((0)) NOT NULL,
   ACP_CODTRA INT NOT NULL,
   ACP_CODTEV INT,
   ACP_FECHA_EVALUACION DATE,
   ACP_NOTA_EVALUACION NUMBER(5, 2),
   ACP_RESULTADO_EVALUACION VARCHAR2(100 CHAR),
   ACP_CODFDD INT,
   ACP_ESTADO VARCHAR2(10 CHAR) DEFAULT ('Pendiente') NOT NULL,
   ACP_FECHA_FINALIZACION DATE,
   ACP_COMENTARIO_FINALIZACION VARCHAR2(4000 CHAR),
   ACP_PROPERTY_BAG_DATA CLOB,
   ACP_USUARIO_GRABACION VARCHAR2(50 CHAR),
   ACP_FECHA_GRABACION DATE,
   ACP_USUARIO_MODIFICACION VARCHAR2(50 CHAR),
   ACP_FECHA_MODIFICACION DATE
);

COMMENT ON TABLE OBD_ACP_ACTIVIDADES_PRG IS 'Tabla que almacena las actividades de los participantes de un programa de onboarding';

COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_CODIGO IS 'Código de registro de la actividad de un participante para un programa de onboarding';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_CODPAP IS 'Código del participante de un programa de onboarding';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_NOMBRE IS 'Nombre de la actividad';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_DESCRIPCION IS 'Descripción de la actividad';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_OBJETIVO IS 'Objetivo de la actividad';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_CODETP IS 'Código de Etapa o Fase del programa';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_CODTAC IS 'Código de Tipo de Actividad';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_CODEMP_RESPONSABLE IS 'Código de empleo responsable de la evaluación';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_FECHA_INICIO IS 'Fecha calculada de inicio de la actividad';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_FECHA_FIN IS 'Fecha calculada de finalización de la actividad';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_DURACION IS 'Duración de la actividad';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_UNIDAD_DURACION IS 'Unidad de medida de la duración de la actividad';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_CODPRI IS 'Código de Prioridad de la actividad';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_ORDEN IS 'Orden de esta actividad respecto de las mismas que tienen los mismos requisitos';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_CODTRA IS 'Código de Tipo de Responsable de la actividad';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_CODTEV IS 'Codigo de Tipo de Evaluación de la activdidad (NULL cuando no requiere evaluación)';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_FECHA_EVALUACION IS 'Fecha de evaluación de la actividad';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_NOTA_EVALUACION IS 'Nota de la evaluación dada por el responsable de la actividad';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_RESULTADO_EVALUACION IS 'Determina si la evaluación fue aprobada o no';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_CODFDD IS 'Código de la data del formulario dinámico (cuando está definido según el tipo de evaluación)';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_ESTADO IS 'Estado de la actividad (Pendiente, En Proceso, Finalizada)';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_FECHA_FINALIZACION IS 'Fecha de finalización de la actividad (fecha en el estado cambio a finalizada)';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_COMENTARIO_FINALIZACION IS 'Comentarios de evaluador o quien finaliza la actividad';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_PROPERTY_BAG_DATA IS 'Data de los campos adicionales';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_USUARIO_GRABACION IS 'Usuario que creo el registro';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_FECHA_GRABACION IS 'Fecha en que se creo el registro';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_USUARIO_MODIFICACION IS 'Usuario que modificó por última vez el registro';
COMMENT ON COLUMN OBD_ACP_ACTIVIDADES_PRG.ACP_FECHA_MODIFICACION IS 'Fecha de la última modificacion del registro';
