CREATE TABLE OBD_ETP_ETAPAS_PRG (
   ETP_CODIGO INT NOT NULL,
   ETP_CODGRC INT NOT NULL,
   ETP_NOMBRE VARCHAR2(100 CHAR) NOT NULL,
   ETP_DESCRIPCION VARCHAR2(500 CHAR),
   ETP_ORDEN INT DEFAULT ((0)) NOT NULL,
   ETP_ANTES_PRIMER_DIA NUMBER(1, 0) DEFAULT ((0)) NOT NULL,
   ETP_DURANTE_PRIMER_DIA NUMBER(1, 0) DEFAULT ((0)) NOT NULL,
   ETP_POSTERIOR_PRIMER_DIA NUMBER(1, 0) DEFAULT ((0)) NOT NULL,
   ETP_PERIODO_PRUEBA NUMBER(1, 0) DEFAULT ((0)) NOT NULL,
   ETP_PROPERTY_BAG_DATA CLOB,
   ETP_USUARIO_GRABACION VARCHAR2(50 CHAR),
   ETP_FECHA_GRABACION DATE,
   ETP_USUARIO_MODIFICACION VARCHAR2(50 CHAR),
   ETP_FECHA_MODIFICACION DATE
);

COMMENT ON TABLE OBD_ETP_ETAPAS_PRG IS 'Tabla con las fases o etapas de los programas de Onboarding';

COMMENT ON COLUMN OBD_ETP_ETAPAS_PRG.ETP_CODIGO IS 'Código de la etapa del programa';
COMMENT ON COLUMN OBD_ETP_ETAPAS_PRG.ETP_CODGRC IS 'Código de grupo corporativo';
COMMENT ON COLUMN OBD_ETP_ETAPAS_PRG.ETP_NOMBRE IS 'Nombre de la etapa del programa';
COMMENT ON COLUMN OBD_ETP_ETAPAS_PRG.ETP_DESCRIPCION IS 'Descripción de la etapa del programa';
COMMENT ON COLUMN OBD_ETP_ETAPAS_PRG.ETP_ORDEN IS 'Orden de esta etapa respecto de las demás';
COMMENT ON COLUMN OBD_ETP_ETAPAS_PRG.ETP_ANTES_PRIMER_DIA IS '¿Corresponde con actividades antes del primer día de trabajo?';
COMMENT ON COLUMN OBD_ETP_ETAPAS_PRG.ETP_DURANTE_PRIMER_DIA IS '¿Corresponde con actividades durante el primer día de trabajo?';
COMMENT ON COLUMN OBD_ETP_ETAPAS_PRG.ETP_POSTERIOR_PRIMER_DIA IS '¿Corresponde con actividades posteriores al primer día de trabajo?';
COMMENT ON COLUMN OBD_ETP_ETAPAS_PRG.ETP_PERIODO_PRUEBA IS 'Esta fase está contenida en el período de prueba';
COMMENT ON COLUMN OBD_ETP_ETAPAS_PRG.ETP_PROPERTY_BAG_DATA IS 'Data de los campos adicionales';
COMMENT ON COLUMN OBD_ETP_ETAPAS_PRG.ETP_USUARIO_GRABACION IS 'Usuario que creo el registro';
COMMENT ON COLUMN OBD_ETP_ETAPAS_PRG.ETP_FECHA_GRABACION IS 'Fecha en que se creo el registro';
COMMENT ON COLUMN OBD_ETP_ETAPAS_PRG.ETP_USUARIO_MODIFICACION IS 'Usuario que modificó por última vez el registro';
COMMENT ON COLUMN OBD_ETP_ETAPAS_PRG.ETP_FECHA_MODIFICACION IS 'Fecha de la última modificacion del registro';
