CREATE TABLE OBD_PAL_PLANT_ALCANCES (
   PAL_CODIGO INT NOT NULL,
   PAL_CODPPR INT NOT NULL,
   PAL_TIPO VARCHAR2(10 CHAR) NOT NULL,
   PAL_CODTPP INT,
   PAL_CODPUE INT,
   PAL_CODCDT INT,
   PAL_CODUNI INT,
   PAL_PROPERTY_BAG_DATA CLOB,
   PAL_USUARIO_GRABACION VARCHAR2(50 CHAR),
   PAL_FECHA_GRABACION DATE,
   PAL_USUARIO_MODIFICACION VARCHAR2(50 CHAR),
   PAL_FECHA_MODIFICACION DATE
);

COMMENT ON TABLE OBD_PAL_PLANT_ALCANCES IS 'Tabla que almacena el alcance para la Plantilla del programa';

COMMENT ON COLUMN OBD_PAL_PLANT_ALCANCES.PAL_CODIGO IS 'Código de registro de alcance para la plantilla de programa de onboarding';
COMMENT ON COLUMN OBD_PAL_PLANT_ALCANCES.PAL_CODPPR IS 'Código de plantilla de programa de onboarding';
COMMENT ON COLUMN OBD_PAL_PLANT_ALCANCES.PAL_TIPO IS 'Tipo de Alcance';
COMMENT ON COLUMN OBD_PAL_PLANT_ALCANCES.PAL_CODTPP IS 'Código de Tipo de Puesto';
COMMENT ON COLUMN OBD_PAL_PLANT_ALCANCES.PAL_CODPUE IS 'Código de Puesto';
COMMENT ON COLUMN OBD_PAL_PLANT_ALCANCES.PAL_CODCDT IS 'Código del centro de trabajo';
COMMENT ON COLUMN OBD_PAL_PLANT_ALCANCES.PAL_CODUNI IS 'Código de la unidad organizativa';
COMMENT ON COLUMN OBD_PAL_PLANT_ALCANCES.PAL_PROPERTY_BAG_DATA IS 'Data de los campos adicionales';
COMMENT ON COLUMN OBD_PAL_PLANT_ALCANCES.PAL_USUARIO_GRABACION IS 'Usuario que creo el registro';
COMMENT ON COLUMN OBD_PAL_PLANT_ALCANCES.PAL_FECHA_GRABACION IS 'Fecha en que se creo el registro';
COMMENT ON COLUMN OBD_PAL_PLANT_ALCANCES.PAL_USUARIO_MODIFICACION IS 'Usuario que modificó por última vez el registro';
COMMENT ON COLUMN OBD_PAL_PLANT_ALCANCES.PAL_FECHA_MODIFICACION IS 'Fecha de la última modificacion del registro';
