CREATE TABLE OBD_PNA_PLANT_NOTIFICACION_ACT (
   PNA_CODIGO INT NOT NULL,
   PNA_CODENO INT NOT NULL,
   PNA_CODPAC INT NOT NULL,
   PNA_USA_FECHA_INICIO NUMBER(1, 0) DEFAULT ((0)) NOT NULL,
   PNA_OFFSET_INICIO INT,
   PNA_OFFSET_FIN INT,
   PNA_SUBJECT VARCHAR2(250 CHAR) NOT NULL,
   PNA_BODY VARCHAR2(4000 CHAR) NOT NULL,
   PNA_ENVIA_CONTRATADO NUMBER(1, 0) DEFAULT ((1)) NOT NULL,
   PNA_ENVIA_JEFE NUMBER(1, 0) DEFAULT ((1)) NOT NULL,
   PNA_ENVIA_RESPONSABLE NUMBER(1, 0) DEFAULT ((1)) NOT NULL,
   PNA_PROPERTY_BAG_DATA CLOB,
   PNA_USUARIO_GRABACION VARCHAR2(50 CHAR),
   PNA_FECHA_GRABACION DATE,
   PNA_USUARIO_MODIFICACION VARCHAR2(50 CHAR),
   PNA_FECHA_MODIFICACION DATE
);

COMMENT ON TABLE OBD_PNA_PLANT_NOTIFICACION_ACT IS 'Tabla que almacena las configuraciones de las notificaciones para las actividades de la plantilla';

COMMENT ON COLUMN OBD_PNA_PLANT_NOTIFICACION_ACT.PNA_CODIGO IS 'Código de la configuración de las notificaciones de la actividad de la plantilla';
COMMENT ON COLUMN OBD_PNA_PLANT_NOTIFICACION_ACT.PNA_CODENO IS 'Código de Evento Notificable';
COMMENT ON COLUMN OBD_PNA_PLANT_NOTIFICACION_ACT.PNA_CODPAC IS 'Código de Actividad de la plantilla de programas de onboarding';
COMMENT ON COLUMN OBD_PNA_PLANT_NOTIFICACION_ACT.PNA_USA_FECHA_INICIO IS 'Determina cual desplazamiento utiliza, si el de fecha inicio o fecha fin';
COMMENT ON COLUMN OBD_PNA_PLANT_NOTIFICACION_ACT.PNA_OFFSET_INICIO IS 'Desplazamiento en dias antes o despues de la fecha de inicio ';
COMMENT ON COLUMN OBD_PNA_PLANT_NOTIFICACION_ACT.PNA_OFFSET_FIN IS 'Desplazamiento en dias antes o despues de la fecha de finalizacion';
COMMENT ON COLUMN OBD_PNA_PLANT_NOTIFICACION_ACT.PNA_SUBJECT IS 'Asunto de la notificación';
COMMENT ON COLUMN OBD_PNA_PLANT_NOTIFICACION_ACT.PNA_BODY IS 'Cuerpo Markdown de la notificación';
COMMENT ON COLUMN OBD_PNA_PLANT_NOTIFICACION_ACT.PNA_ENVIA_CONTRATADO IS 'Determina si la notificación se envía al empleado contratado';
COMMENT ON COLUMN OBD_PNA_PLANT_NOTIFICACION_ACT.PNA_ENVIA_JEFE IS 'Determina si la notificación se envía al jefe inmediato superior del empleado';
COMMENT ON COLUMN OBD_PNA_PLANT_NOTIFICACION_ACT.PNA_ENVIA_RESPONSABLE IS 'Determina si la notificación se envía al responsable de la actividad';
COMMENT ON COLUMN OBD_PNA_PLANT_NOTIFICACION_ACT.PNA_PROPERTY_BAG_DATA IS 'Data de los campos adicionales';
COMMENT ON COLUMN OBD_PNA_PLANT_NOTIFICACION_ACT.PNA_USUARIO_GRABACION IS 'Usuario que creo el registro';
COMMENT ON COLUMN OBD_PNA_PLANT_NOTIFICACION_ACT.PNA_FECHA_GRABACION IS 'Fecha en que se creo el registro';
COMMENT ON COLUMN OBD_PNA_PLANT_NOTIFICACION_ACT.PNA_USUARIO_MODIFICACION IS 'Usuario que modificó por última vez el registro';
COMMENT ON COLUMN OBD_PNA_PLANT_NOTIFICACION_ACT.PNA_FECHA_MODIFICACION IS 'Fecha de la última modificacion del registro';
