CREATE OR REPLACE TRIGGER OBD_TEV_IDENTITY
   BEFORE INSERT ON OBD_TEV_TIPOS_EVALUACION
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW WHEN (NVL(NEW.TEV_CODIGO, 0) = 0)
Begin
   SELECT OBD_TEV_SEQ.NEXTVAL INTO :NEW.TEV_CODIGO FROM DUAL;
End;
/
