CREATE OR REPLACE TRIGGER OBD_ACP_IDENTITY
   BEFORE INSERT ON OBD_ACP_ACTIVIDADES_PRG
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW WHEN (NVL(NEW.ACP_CODIGO, 0) = 0)
Begin
   SELECT OBD_ACP_SEQ.NEXTVAL INTO :NEW.ACP_CODIGO FROM DUAL;
End;
/
