CREATE OR REPLACE TRIGGER OBD_PNA_IDENTITY
   BEFORE INSERT ON OBD_PNA_PLANT_NOTIFICACION_ACT
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW WHEN (NVL(NEW.PNA_CODIGO, 0) = 0)
Begin
   SELECT OBD_PNA_SEQ.NEXTVAL INTO :NEW.PNA_CODIGO FROM DUAL;
End;
/
