CREATE OR REPLACE TRIGGER OBD_PRI_IDENTITY
   BEFORE INSERT ON OBD_PRI_PRIORIDADES
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW WHEN (NVL(NEW.PRI_CODIGO, 0) = 0)
Begin
   SELECT OBD_PRI_SEQ.NEXTVAL INTO :NEW.PRI_CODIGO FROM DUAL;
End;
/
