CREATE OR REPLACE TRIGGER OBD_PAP_IDENTITY
   BEFORE INSERT ON OBD_PAP_PARTICIPANTES_PRG
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW WHEN (NVL(NEW.PAP_CODIGO, 0) = 0)
Begin
   SELECT OBD_PAP_SEQ.NEXTVAL INTO :NEW.PAP_CODIGO FROM DUAL;
End;
/
