CREATE OR REPLACE TRIGGER OBD_PAL_IDENTITY
   BEFORE INSERT ON OBD_PAL_PLANT_ALCANCES
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW WHEN (NVL(NEW.PAL_CODIGO, 0) = 0)
Begin
   SELECT OBD_PAL_SEQ.NEXTVAL INTO :NEW.PAL_CODIGO FROM DUAL;
End;
/
