CREATE OR REPLACE TRIGGER OBD_NAP_IDENTITY
   BEFORE INSERT ON OBD_NAP_NOTIF_ACTIVIDAD_PRG
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW WHEN (NVL(NEW.NAP_CODIGO, 0) = 0)
Begin
   SELECT OBD_NAP_SEQ.NEXTVAL INTO :NEW.NAP_CODIGO FROM DUAL;
End;
/
