CREATE OR REPLACE TRIGGER OBD_ETP_IDENTITY
   BEFORE INSERT ON OBD_ETP_ETAPAS_PRG
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW WHEN (NVL(NEW.ETP_CODIGO, 0) = 0)
Begin
   SELECT OBD_ETP_SEQ.NEXTVAL INTO :NEW.ETP_CODIGO FROM DUAL;
End;
/
