CREATE OR REPLACE TRIGGER OBD_TAC_IDENTITY
   BEFORE INSERT ON OBD_TAC_TIPOS_ACTIVIDAD
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW WHEN (NVL(NEW.TAC_CODIGO, 0) = 0)
Begin
   SELECT OBD_TAC_SEQ.NEXTVAL INTO :NEW.TAC_CODIGO FROM DUAL;
End;
/
