CREATE OR REPLACE TRIGGER OBD_PPR_IDENTITY
   BEFORE INSERT ON OBD_PPR_PLANTILLA_PRG
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW WHEN (NVL(NEW.PPR_CODIGO, 0) = 0)
Begin
   SELECT OBD_PPR_SEQ.NEXTVAL INTO :NEW.PPR_CODIGO FROM DUAL;
End;
/
