CREATE OR REPLACE TRIGGER OBD_PAC_IDENTITY
   BEFORE INSERT ON OBD_PAC_PLANT_ACTIVIDADES
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW WHEN (NVL(NEW.PAC_CODIGO, 0) = 0)
Begin
   SELECT OBD_PAC_SEQ.NEXTVAL INTO :NEW.PAC_CODIGO FROM DUAL;
End;
/
